name: Docker Build & Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Login en Docker Hub
      uses: docker/login-action@v1
        
    - name: Construir imagen Docker
      run: docker build -t tu_usuario/nombre_de_imagen:latest .
    
    - name: Publicar imagen en Docker Hub
      run: docker push tu_usuario/nombre_de_imagen:latest
