name: Node test

on:
  push:
    branches:
      - main

jobs:
  imprimir_informacion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Imprimir información
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        run: 
        echo "Nombre completo: Cristian Diaz de Leon"
        echo "Versión de Node utilizada: $(node --version)"
        echo "Expediente: 715232"
